# Generated by Django 3.2.9 on 2022-03-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='problemcost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProblemDescription', models.CharField(max_length=100)),
                ('Cost', models.IntegerField()),
            ],
            options={
                'db_table': 'problemcost',
            },
        ),
    ]
