# Generated by Django 3.2.9 on 2022-03-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_problemcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='download.jpg', null=True, upload_to='profile_pic/CustomerProfilePic/'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='profile_pic',
            field=models.ImageField(blank=True, default='download.jpg', null=True, upload_to='profile_pic/MechanicProfilePic/'),
        ),
    ]
